### ISSUE TITLE
Can't watch next episode

### ISSUE THREAD

**Issue by juanscv** [amilajack/popcorn-time-desktop#167]
After finishing an TV episode, the next one doesn't load up correctly. It either always loads the one I just watched when switching to a new ep, or it loads only audio, with placeholder image on the viewer.

PT 0.0.5-alpha
Mac OS Sierra Golden Master

**Comment by amilajack** [comment]
This is very interesting behavior but I experience similar behavior to this sometimes. In order to solve this we might need to do some debugging on your part, as I don't think I can reproduce them.

What are the exact steps you took to produce this error?

Also it would be helpful if you could build this project from source and view the errors that are logged to the console.

**Comment by amilajack** [comment]
@juanscv did this work out for you?
