### ISSUE TITLE
Some video codecs are not supported

### ISSUE THREAD

**Issue by mattjis** [amilajack/popcorn-time-desktop#171]
Not sure if this is a known issue or not but the audio works fine when using VLC instead. Could it be the video format? (Only happens on some videos)

If you want to test or anything I was trying to watch: South Park > Season 18 > Episode 2 (720p)
I'm also using the latest public beta version 0.05 on MacOS Sierra.

Thanks for all you do. Super hyped for the next release, this app is great!

**Comment by karuppiah7890** [comment]
@mattjis Did you try increasing the volume in VLC while watching it ? I think the volume was too low in the default, but VLC has the ability to increase the volume to 200% so, I think you kept the volume higher than 100% and you got to listen to the audio

**Comment by amilajack** [comment]
@mattjis for some reason I didn't see this issue when it was created so sorry for the late response.

I've also experienced this as well and I believe that it has to do with the [audio codec](https://github.com/RSATom/WebChimera.js/issues/69#issuecomment-236515014). Recently I've been held back by a number of breaking changes in the [ui-design-implementation branch](https://github.com/amilajack/popcorn-time-desktop/tree/ui-design-implementation) (which I highly recommend checking out).

**Comment by karuppiah7890** [comment]
@amilajack Actually, I meant the 100% volume of the audio of the file itself was low. And it was better in VLC. This happened to me in the case of Avengers movie.

**Comment by amilajack** [comment]
I see. There this was what I experienced. Not sure if there is a way of fixing this. This has more to do with webtorrent (I think)

**Comment by karuppiah7890** [comment]
Yes. We can't fix the problem in the files. We just have to recommend people to use VLC. Or, we need to find a way to boost the volume in the application's default player itself.

**Comment by mattjis** [comment]
Unfortunately I can only do front end development at the moment although i'm trying to learn more javascript etc.. I could help design anything you need though as i've been designing for many years.

> the ui-design-implementation branch (which I highly recommend checking)
I would love to try out any new version. I've been refreshing the releases page daily waiting for 0.06 to come out haha as I have no idea how to "build" from the source files.

> 1. What do you notice that is different about this client?
- I switched to Mac OS Sierra very early on and it broke both the Popcorn Time apps I had previously. Someone on reddit told me to try this version out to see if it would work. Which it did! 

So it's basically the only one that actually works anymore, and it's being rapidly updated which is very pleasing to know as it's only going to get better from here!

- I also feel safe using it (as in I trust the people developing it) - there was a bit of sketchy stuff going on with all the other apps.

> 2. How can it be improved?
I'd love it if all videos began in the default player and from there we get the choice to move it elsewhere (ChromeCast / AppleTV / VLC) and back without any hassle or redownload. 

I always forget to click the correct output source (or change my mind mid way through) and have to completely quit the app and re open it just to get the correct output :(

Other than that everything is great! As soon as the redesign hits this will be #1 for sure

**Comment by amilajack** [comment]
> I actually tried to slightly "retouch" an old popcorn time last year but they never got back to me:

I'm desperate for new designs! It would be great if you could join [our discussion on the UI redesign](https://github.com/amilajack/popcorn-time-desktop/issues/145) and the [initial work for some animation](https://github.com/amilajack/popcorn-time-desktop/issues/145#issuecomment-247692463). 

>  I could help design anything you need though as i've been designing for many years.

Great! [Here's the repo](https://github.com/amilajack/popcorn-time-desktop-design) for the sketch designs. Any redesigns that you can do are welcome and encouraged.

> I've been refreshing the releases page daily waiting for 0.06 to come out haha as I have no idea how to "build" from the source files.

This makes me feel really guilty because I haven't been contributing much to this project recently :( I've been working on [another project](https://github.com/amilajack/eslint-plugin-flowtype-errors) that I made to help me with the development of this project. Its funny how that project is more popular than this one LOL. But this weekend I'll finish some work on the ui-design-implementaion branch.

> I'd love it if all videos began in the default player and from there we get the choice to move it elsewhere (ChromeCast / AppleTV / VLC) and back without any hassle or redownload.

I totally agree with this. I don't think this will be too hard to implement. It will likely require a rewrite of the playback implementation but I was planning on doing that anyways.

On a side note, I would really appreciate a dribbble invitation 😆 I've tried so hard to get one but never did :(

> Someone on reddit told me to try this version out to see if it would work. Which it did!

That may have been me! It would be great if you could upvote the comment and spread the word on the forum somehow. I really need testers for 0.0.6 because it is pretty much a rewrite of the entire front-end and there are a lot of bugs. Right now though I think it would be good to tell people to try out the 0.0.5 release. 0.0.6 isn't very stable.

> I would love to try out any new version. I've been refreshing the releases page daily waiting for 0.06 to come out haha as I have no idea how to "build" from the source files.

This is actually much simpler than it seems. I've had a terrible experience with installing nodejs/npm projects. Half the time it never works. With this project, I wanted to make sure that everything worked without the developer having to do anything. You should be able to paste in these bash commands and it should work:

```bash
git clone https://github.com/amilajack/popcorn-time-desktop.git
cd popcorn-time-desktop

# Checkout the UI Design Implementation Branch
git checkout ui-design-implementation

# Install dependencies
# Have a cup of coffee ☕️ this might take a while
# Remember to `npm rebuild` if necessary
npm install

# Customize Build
# Feel free to enable flags and configs in the `.env` file (this is totally optional)
vi .env

# Developement build
npm run dev

# Production build
npm run package
```

**Comment by mattjis** [comment]
> I'm desperate for new designs! It would be great if you could join our discussion on the UI redesign and the initial work for some animation.

I'm very keen to do this i'll try to come up with something nice this week.

> On a side note, I would really appreciate a dribbble invitation 😆 I've tried so hard to get one but never did :(

Yeah for sure send me a link to your profile and i'll get you invited!

I'll also figure out how to build from github (Just need to install brew & node) and hopefully be able to report any problems I find back to you. 

Is the best way to report bugs in this issues section?

**Comment by amilajack** [comment]
[Here's](https://dribbble.com/amilajack) my dribbble. Bugs should reported where they'll be easiest for me and other future contributors to find. So all issues regarding codecs not being supported should go in this issue. Each new issue should be created if it doesn't exist. I think that will really help.

Also I just uploaded a precompiled version of the `ui-design-implementation` branch 🎉 Note that it is far from being finished. It works for the most part but there are some situations where torrents don't play. It would be great if you could look into what user actions prevent torrents/playback from working correctly

**Comment by karuppiah7890** [comment]
>Let me know if you guys are interested in contributing

I am totally into contributing to FOSS ! :smile:
