### ISSUE TITLE
Remove jQuery dependency and use more efficiency DOM selector

### ISSUE THREAD

**Issue by thangngoc89** [amilajack/popcorn-time-desktop#48]
Hi, 

First of all, thanks for working on this. After looking around your codebase, I have some suggestions: 

- Remove jQuery. I don't see why you need jQuery in `/app/api/Player.js` . 
- Don't use document.querySelector for everything, for ex:

  - `document.querySelector('.plyr')` can be `document.getElementsByClassName('plyr').first`. I admit it's more to type but if you do some benchmark, you'll see the different between them

I can send a PR if you're interested in this

**Comment by amilajack** [comment]
jQuery is actually required by bootstrap 4. And a PR for that would definitely be welcome! But make sure the PR is for the release-0.0.3-alpha branch to avoid any merge conflicts later on.

**Comment by amilajack** [comment]
Actually would `document.getElementById` be even faster?

**Comment by ZakariaRidouh** [comment]
Yeah, `document.getElementById` would actually be faster by a few ms, so why not use it?

I guess because you can have multiple elements with the same class so it has to keep checking for the same think through all the nodes, but, with getElementById, it stops after finding the first one (and only one). 
I guess you can use `document.getElementsByClassName('class').first` if you don't have control over the generated elements (and they only have class identifiers) but you can always set the ID yourself if you want.

**Comment by thangngoc89** [comment]
OK. Didn't know you're using bootstrap. But why does it require bootstrap? I usually use bootstrap 3 stylesheet + react-bootstrap for its components.

When I get back to my computer, I'll make some benchmark for you

**Comment by amilajack** [comment]
Good question. Choosing between twbs 3 and 4 was a hard decision.

Because electron is a controlled environment, as opposed to the browser, we know exactly what our production environment is going to be. We dont have to worry about things such as backwards compatibility (tho backwards compat with twbs 4 is supported, this is a general goal of this project: use experimental things that work well). I invested in boostrap 4 because I really liked how it supported modern css standards natively, such as flexbox. It also has more modern components that reflect recent trends in UI. Some of those include the new card component. We also wouldnt have to migrate to twbs 4 in the future. Also, I expected that there would be some react bindings for twbs 4, twbs being in beta. [reactstrap](https://reactstrap.github.io/) seems like a nice alternative to react-bootstrap. In fact its coverage seems to be much better. What do you think?

**Comment by thangngoc89** [comment]
reactstrap looks promising. Correct me if I'm wrong, but I checked your codebase and I can see that you didn't use the bootstrap part that requires jQuery. So I can say you can easily drop it.

**Comment by thangngoc89** [comment]
Oops. jsperf.com was downed (for a few months now). No idea how to make a benchmark without it.

**Comment by amilajack** [comment]
@thangngoc89 sounds good. Could you drop it in your PR?

**Comment by thangngoc89** [comment]
@amilajack yeah. I'll send a PR as soon as I can setup the dev environment. Installing ElementaryOS...

**Comment by amilajack** [comment]
Ahh my favorite linux distro by far. Good choice!

**Comment by amilajack** [comment]
Migrated to [reactstrap](https://github.com/reactstrap/reactstrap/), which doesnt have a dependency on jQuery. Fixed in release 0.0.4
